apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang
  name: golang
spec:
  ports:
  - name: 80-8082
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: golang
  type: NodePort
status:
  loadBalancer: {}

